// Part 2: Service pages + Booking + Pricing
import { writeFileSync, mkdirSync } from 'fs';

const PHONE = '+44 7704 503507';
const PHONE_LINK = 'tel:+447704503507';
const EMAIL = 'Runyruny@ukr.net';
const EMAIL_LINK = 'mailto:Runyruny@ukr.net';

const header = `<header class="header" id="header"><div class="header__inner"><a href="/" class="header__logo">The Bereza <span>Method</span></a><button class="nav-toggle" aria-label="Toggle navigation"><span></span><span></span><span></span></button><nav class="nav" id="nav"><a href="/about/" class="nav__link">About</a><a href="/services/" class="nav__link">Services</a><a href="/pricing/" class="nav__link">Pricing</a><a href="/areas/massage-therapist-kensington/" class="nav__link">Areas</a><a href="/blog/" class="nav__link">Blog</a><a href="/contact/" class="nav__link">Contact</a><a href="/book/" class="nav__cta">Book Now</a></nav></div></header>`;
const footer = `<footer class="footer"><div class="container"><div class="footer__grid"><div><div class="footer__brand-name">The Bereza <span>Method</span></div><p class="footer__desc">London's premier mobile massage therapy service.</p><p style="margin-top:var(--space-md);"><a href="${PHONE_LINK}" style="color:var(--color-gold);">${PHONE}</a><br><a href="${EMAIL_LINK}" style="color:var(--color-gold);">${EMAIL}</a></p></div><div><h4 class="footer__heading">Services</h4><ul class="footer__links"><li><a href="/services/deep-tissue-massage-london/">Deep Tissue</a></li><li><a href="/services/swedish-massage-london/">Swedish</a></li><li><a href="/services/hot-stone-massage-london/">Hot Stone</a></li><li><a href="/services/aromatherapy-massage-london/">Aromatherapy</a></li><li><a href="/services/sensual-massage-london/">Sensual</a></li><li><a href="/services/divine-alignment-massage-london/">Divine Alignment</a></li><li><a href="/services/sports-massage-london/">Sports</a></li><li><a href="/services/couples-massage-london/">Couples</a></li><li><a href="/services/lymphatic-drainage-london/">Lymphatic</a></li></ul></div><div><h4 class="footer__heading">Quick Links</h4><ul class="footer__links"><li><a href="/about/">About</a></li><li><a href="/pricing/">Pricing</a></li><li><a href="/book/">Book Online</a></li><li><a href="/faq/">FAQ</a></li><li><a href="/reviews/">Reviews</a></li><li><a href="/gift-vouchers/">Gift Vouchers</a></li><li><a href="/quiz/">Free Quiz</a></li></ul></div><div><h4 class="footer__heading">Areas</h4><ul class="footer__links"><li><a href="/areas/massage-therapist-kensington/">Kensington</a></li><li><a href="/areas/massage-therapist-chelsea/">Chelsea</a></li><li><a href="/areas/massage-therapist-mayfair/">Mayfair</a></li><li><a href="/areas/massage-therapist-paddington/">Paddington</a></li><li><a href="/areas/massage-therapist-canary-wharf/">Canary Wharf</a></li><li><a href="/areas/massage-therapist-knightsbridge/">Knightsbridge</a></li><li><a href="/areas/massage-therapist-notting-hill/">Notting Hill</a></li><li><a href="/areas/massage-therapist-soho/">Soho</a></li></ul></div></div><div class="footer__bottom"><p>&copy; 2026 The Bereza Method. All rights reserved. <a href="/terms/">Terms</a> · <a href="/privacy/">Privacy</a></p></div></div></footer>`;
const trustBar = `<div class="trust-bar"><div class="trust-bar__inner"><div class="trust-bar__item"><span>✓</span> 10+ Years Experience</div><div class="trust-bar__item"><span>✓</span> Same-Day Available</div><div class="trust-bar__item"><span>✓</span> 8am-8pm Daily</div><div class="trust-bar__item"><span>✓</span> No Travel Fees</div></div></div>`;

function pg(title, desc, canonical, body, schema = '') {
    return `<!DOCTYPE html>\n<html lang="en">\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <title>${title}</title>\n  <meta name="description" content="${desc}">\n  <link rel="canonical" href="https://massage-london-bereza.vercel.app${canonical}">\n  <link rel="stylesheet" href="/css/global.css">\n  ${schema}\n</head>\n<body>\n  ${header}\n  ${body}\n  ${footer}\n  <script src="/js/main.js"></script>\n</body>\n</html>`;
}

function servicePage(s) {
    const schema = `<script type="application/ld+json">{"@context":"https://schema.org","@type":"Service","name":"${s.name}","description":"${s.desc}","provider":{"@type":"MassageTherapy","name":"The Bereza Method","telephone":"+447704503507"},"areaServed":{"@type":"City","name":"London"},"offers":{"@type":"Offer","price":"${s.price}","priceCurrency":"GBP"}}</script>`;
    return pg(s.title, s.metaDesc, `/services/${s.slug}/`, `
  <section class="page-hero"><div class="container"><p class="subtitle">${s.tag}</p><h1>${s.h1}</h1><p>${s.heroDesc}</p></div></section>
  ${trustBar}
  <section class="section section--white"><div class="container"><div class="grid grid--2" style="align-items:center;gap:var(--space-4xl);"><div class="fade-in-left"><p class="subtitle">About This Treatment</p><h2>${s.subhead}</h2>${s.content}</div><div class="fade-in-right"><img src="${s.image}" alt="${s.imageAlt}" style="width:100%;border-radius:var(--radius-lg);box-shadow:var(--shadow-lg);"></div></div></div></section>
  <section class="section section--cream"><div class="container"><div class="section-header fade-in"><p class="subtitle">Pricing</p><h2>${s.name} Pricing</h2></div><div class="grid grid--3" style="max-width:800px;margin:0 auto;"><div class="card fade-in" style="text-align:center;"><h4>60 Minutes</h4><div style="font-size:2rem;font-family:var(--ff-heading);color:var(--color-gold);margin:var(--space-md) 0;">From £${s.price}</div><a href="/book/" class="btn btn--primary" style="width:100%;">Book Now</a></div><div class="card fade-in" style="text-align:center;"><h4>90 Minutes</h4><div style="font-size:2rem;font-family:var(--ff-heading);color:var(--color-gold);margin:var(--space-md) 0;">From £${s.price90 || Math.round(s.price * 1.4)}</div><a href="/book/" class="btn btn--primary" style="width:100%;">Book Now</a></div><div class="card fade-in" style="text-align:center;"><h4>2 Hours</h4><div style="font-size:2rem;font-family:var(--ff-heading);color:var(--color-gold);margin:var(--space-md) 0;">From £${s.price120 || Math.round(s.price * 1.8)}</div><a href="/book/" class="btn btn--primary" style="width:100%;">Book Now</a></div></div></div></section>
  <section class="cta-section"><div class="container"><p class="subtitle">Book Today</p><h2>Same-Day ${s.name} in London</h2><p>Available 8am-8pm, 7 days a week across Central London.</p><div style="display:flex;gap:var(--space-md);justify-content:center;flex-wrap:wrap;"><a href="/book/" class="btn btn--primary btn--lg">Book Now</a><a href="${PHONE_LINK}" class="btn btn--outline btn--lg" style="border-color:var(--color-cream);color:var(--color-cream);">Call ${PHONE}</a></div></div></section>`,
        schema);
}

const services = [
    { slug: 'deep-tissue-massage-london', name: 'Deep Tissue Massage', tag: 'Deep Tissue Massage', h1: 'Deep Tissue Massage London', title: 'Deep Tissue Massage London | Same-Day Home Visits', metaDesc: `Deep tissue massage London by Iryna Bereza. Chronic neck, back, shoulder pain relief. Same-day mobile visits across Kensington, Mayfair, Paddington. From £65. Book: ${PHONE}`, desc: 'Clinical deep tissue therapy for chronic pain', heroDesc: 'Clinical-grade deep tissue therapy delivered to your home, hotel or office. 50% pain reduction guaranteed.', subhead: 'Precision Therapy for Chronic Pain', price: 65, price90: 95, price120: 130, image: '/images/deep-tissue.png', imageAlt: 'Deep tissue massage therapy London by Iryna Bereza targeting chronic back pain', content: '<p style="font-size:var(--fs-body-lg);line-height:var(--lh-relaxed);">Deep tissue massage uses slow, firm strokes and sustained pressure to reach the deeper layers of muscle and fascia. It\'s the most effective treatment for chronic neck, shoulder and back pain — especially for London desk workers.</p><ul style="list-style:none;margin-top:var(--space-xl);"><li style="padding:var(--space-xs) 0;">✦ Chronic neck, back & shoulder pain relief</li><li style="padding:var(--space-xs) 0;">✦ Breaks up adhesions & scar tissue</li><li style="padding:var(--space-xs) 0;">✦ Improves range of motion</li><li style="padding:var(--space-xs) 0;">✦ Reduces inflammation</li><li style="padding:var(--space-xs) 0;">✦ Resets pain signalling</li></ul>' },
    { slug: 'swedish-massage-london', name: 'Swedish Massage', tag: 'Swedish Massage', h1: 'Swedish Massage London', title: 'Swedish Massage London | Stress Relief Home Visits', metaDesc: `Swedish therapeutic massage London. Full-body stress relief, nervous system reset, better sleep. Same-day home visits by Iryna Bereza. From £55. 8am-8pm daily.`, desc: 'Full-body stress relief & relaxation', heroDesc: 'Full-body stress relief, nervous system reset, and better sleep. Same-day home visits.', subhead: 'Total Relaxation & Stress Relief', price: 55, price90: 85, price120: 115, image: '/images/swedish.png', imageAlt: 'Swedish therapeutic massage London full body stress relief home visit', content: '<p style="font-size:var(--fs-body-lg);line-height:var(--lh-relaxed);">Swedish massage uses long, flowing strokes to activate the parasympathetic nervous system — shifting your body from "fight or flight" to deep rest. The gold standard for stress relief.</p><ul style="list-style:none;margin-top:var(--space-xl);"><li style="padding:var(--space-xs) 0;">✦ Full-body stress relief</li><li style="padding:var(--space-xs) 0;">✦ Nervous system reset</li><li style="padding:var(--space-xs) 0;">✦ Better sleep quality</li><li style="padding:var(--space-xs) 0;">✦ Cortisol reduction up to 31%</li><li style="padding:var(--space-xs) 0;">✦ Serotonin boost for mood regulation</li></ul>' },
    { slug: 'hot-stone-massage-london', name: 'Hot Stone Massage', tag: 'Hot Stone Massage', h1: 'Hot Stone Massage London', title: 'Hot Stone Massage London | Mobile Therapy', metaDesc: 'Hot stone massage London. Heated volcanic basalt stones for deep muscle release. Same-day home and hotel visits by Iryna Bereza. From £70. Kensington, Mayfair, Chelsea.', desc: 'Heated volcanic basalt stones', heroDesc: 'Heated volcanic basalt stones for deep muscle release. Same-day home and hotel visits.', subhead: 'Deep Warmth & Muscle Release', price: 70, price90: 105, price120: 140, image: '/images/hot-stone.png', imageAlt: 'Hot stone massage London heated volcanic basalt stones on back', content: '<p style="font-size:var(--fs-body-lg);line-height:var(--lh-relaxed);">Hot stone massage uses smooth, heated volcanic basalt stones that penetrate deep into muscles — releasing tension your hands can\'t reach. The warmth melts away stress while promoting deep circulation.</p><ul style="list-style:none;margin-top:var(--space-xl);"><li style="padding:var(--space-xs) 0;">✦ Heated volcanic basalt stones</li><li style="padding:var(--space-xs) 0;">✦ Deep muscle penetration</li><li style="padding:var(--space-xs) 0;">✦ Improved blood circulation</li><li style="padding:var(--space-xs) 0;">✦ Stress & anxiety relief</li><li style="padding:var(--space-xs) 0;">✦ Luxury spa experience at home</li></ul>' },
    { slug: 'aromatherapy-massage-london', name: 'Aromatherapy Massage', tag: 'Aromatherapy Massage', h1: 'Aromatherapy Massage London', title: 'Aromatherapy Massage London | Organic Essential Oils', metaDesc: 'Aromatherapy massage London with organic essential oils. Anxiety, burnout, emotional fatigue relief. Mobile visits by Iryna Bereza. From £65. Kensington, Paddington.', desc: 'Organic essential oils therapy', heroDesc: 'Organic essential oil therapy for anxiety, burnout and emotional fatigue.', subhead: 'Healing Through Nature\'s Oils', price: 65, price90: 95, price120: 130, image: '/images/aromatherapy.jpg', imageAlt: 'Aromatherapy massage London organic essential oils and botanical blends', content: '<p style="font-size:var(--fs-body-lg);line-height:var(--lh-relaxed);">Aromatherapy combines therapeutic massage with clinically-proven essential oils. Lavender, bergamot, and chamomile are scientifically shown to reduce anxiety by up to 36% more than massage alone.</p><ul style="list-style:none;margin-top:var(--space-xl);"><li style="padding:var(--space-xs) 0;">✦ Organic certified essential oils</li><li style="padding:var(--space-xs) 0;">✦ Anxiety & burnout relief</li><li style="padding:var(--space-xs) 0;">✦ Emotional fatigue treatment</li><li style="padding:var(--space-xs) 0;">✦ Better sleep quality</li><li style="padding:var(--space-xs) 0;">✦ Personalised oil blends</li></ul>' },
    { slug: 'sensual-massage-london', name: 'Sensual Massage', tag: 'Sensual Massage', h1: 'Sensual Massage London', title: 'Sensual Massage London | Professional Service', metaDesc: 'Professional sensual massage London by Iryna Bereza. Deep relaxation, body awareness, emotional connection. Safe professional boundaries always maintained. From £120.', desc: 'Professional sensual therapy', heroDesc: 'Deep relaxation, body awareness, and emotional connection. Professional boundaries always maintained.', subhead: 'Deep Relaxation & Body Awareness', price: 120, price90: 180, price120: 240, image: '/images/sensual.png', imageAlt: 'Professional sensual massage London deep relaxation and body awareness', content: '<p style="font-size:var(--fs-body-lg);line-height:var(--lh-relaxed);">Sensual massage is a professional therapeutic service focused on awakening the senses, deep relaxation, and heightened body awareness. Professional boundaries are discussed before every session and respected throughout.</p><ul style="list-style:none;margin-top:var(--space-xl);"><li style="padding:var(--space-xs) 0;">✦ Deep full-body relaxation</li><li style="padding:var(--space-xs) 0;">✦ Heightened body awareness</li><li style="padding:var(--space-xs) 0;">✦ Emotional connection & release</li><li style="padding:var(--space-xs) 0;">✦ Safe professional framework</li><li style="padding:var(--space-xs) 0;">✦ Boundaries discussed & respected</li></ul>' },
    { slug: 'divine-alignment-massage-london', name: 'Massage with Divine Alignment', tag: 'Divine Alignment', h1: 'Divine Alignment Massage London', title: 'Divine Alignment Massage London | Energy Healing', metaDesc: 'Massage with Divine Alignment London. Body, mind, spirit harmony. Energy balancing, grounding, spiritual clarity by Iryna Bereza. From £80. Kensington, Chelsea, Paddington.', desc: 'Body, mind, spirit harmony', heroDesc: 'Body, mind and spirit harmony. Energy balancing, grounding and spiritual clarity.', subhead: 'Body, Mind & Spirit Harmony', price: 80, price90: 120, price120: 160, image: '/images/divine-alignment.png', imageAlt: 'Divine alignment massage London energy healing and spiritual balance', content: '<p style="font-size:var(--fs-body-lg);line-height:var(--lh-relaxed);">Massage with Divine Alignment is a holistic wellness treatment that combines physical bodywork with energy balancing techniques. It restores harmony between body, mind, and spirit — accessible to all beliefs and backgrounds.</p><ul style="list-style:none;margin-top:var(--space-xl);"><li style="padding:var(--space-xs) 0;">✦ Energy balancing & grounding</li><li style="padding:var(--space-xs) 0;">✦ Spiritual clarity & peace</li><li style="padding:var(--space-xs) 0;">✦ Physical tension release</li><li style="padding:var(--space-xs) 0;">✦ Emotional healing</li><li style="padding:var(--space-xs) 0;">✦ Accessible to all beliefs</li></ul>' },
    { slug: 'sports-massage-london', name: 'Sports Recovery Massage', tag: 'Sports Massage', h1: 'Sports Massage London', title: 'Sports Massage London | Athletic Recovery', metaDesc: `Sports recovery massage London. Pre-event, post-event for runners and athletes. Same-day mobile visits by Iryna Bereza. From £65. Kensington, Canary Wharf. 8am-8pm.`, desc: 'Athletic recovery & performance', heroDesc: 'Pre-event, post-event recovery for runners and athletes. Same-day mobile visits.', subhead: 'Performance Recovery for Athletes', price: 65, price90: 95, price120: 130, image: '/images/sports.jpg', imageAlt: 'Sports recovery massage London for runner and athlete muscle recovery', content: '<p style="font-size:var(--fs-body-lg);line-height:var(--lh-relaxed);">Sports massage is clinically designed for athletes and active individuals. Whether you\'re preparing for the London Marathon or recovering from CrossFit, Iryna targets the specific muscle groups under stress.</p><ul style="list-style:none;margin-top:var(--space-xl);"><li style="padding:var(--space-xs) 0;">✦ Pre-event & post-event protocols</li><li style="padding:var(--space-xs) 0;">✦ Injury prevention & recovery</li><li style="padding:var(--space-xs) 0;">✦ IT band & runner\'s knee treatment</li><li style="padding:var(--space-xs) 0;">✦ Improved flexibility & range of motion</li><li style="padding:var(--space-xs) 0;">✦ Faster muscle recovery</li></ul>' },
    { slug: 'couples-massage-london', name: 'Couples Massage', tag: 'Couples Massage', h1: 'Couples Massage London', title: 'Couples Massage London | Two Therapists Your Door', metaDesc: 'Couples massage London — two qualified therapists arrive together. Each person chooses own treatment independently. Kensington, Mayfair, Paddington. From £110 combined.', desc: 'Two therapists, two treatments', heroDesc: 'Two qualified therapists arrive together. Each person chooses own treatment independently.', subhead: 'Two Therapists, One Experience', price: 110, price90: 165, price120: 220, image: '/images/couples.jpg', imageAlt: 'Couples massage London two therapists working side by side in home', content: '<p style="font-size:var(--fs-body-lg);line-height:var(--lh-relaxed);">Our couples massage is delivered by two fully qualified, DBS-checked therapists who arrive together. Each person receives a fully personalised treatment — you can each choose different massage types and durations independently.</p><ul style="list-style:none;margin-top:var(--space-xl);"><li style="padding:var(--space-xs) 0;">✦ Two qualified therapists arrive together</li><li style="padding:var(--space-xs) 0;">✦ Each person chooses own treatment</li><li style="padding:var(--space-xs) 0;">✦ Perfect for anniversaries & special occasions</li><li style="padding:var(--space-xs) 0;">✦ Side-by-side treatment in your home</li><li style="padding:var(--space-xs) 0;">✦ All equipment & oils provided</li></ul>' },
    { slug: 'lymphatic-drainage-london', name: 'Lymphatic Drainage Massage', tag: 'Lymphatic Drainage', h1: 'Lymphatic Drainage Massage London', title: 'Lymphatic Drainage Massage London | Mobile', metaDesc: 'Lymphatic drainage massage London. Reduce swelling, boost immunity, post-surgery support. Same-day visits by Iryna Bereza. From £65. Kensington, Chelsea, Mayfair.', desc: 'Reduce swelling & boost immunity', heroDesc: 'Reduce swelling, boost immunity, and support post-surgery recovery.', subhead: 'Detoxify & Heal', price: 65, price90: 95, price120: 130, image: '/images/lymphatic.png', imageAlt: 'Lymphatic drainage massage London gentle rhythmic technique', content: '<p style="font-size:var(--fs-body-lg);line-height:var(--lh-relaxed);">Lymphatic drainage uses gentle, rhythmic pumping techniques to stimulate your lymphatic system — reducing swelling, boosting immunity, and supporting post-surgical recovery.</p><ul style="list-style:none;margin-top:var(--space-xl);"><li style="padding:var(--space-xs) 0;">✦ Reduce swelling & fluid retention</li><li style="padding:var(--space-xs) 0;">✦ Boost immune system function</li><li style="padding:var(--space-xs) 0;">✦ Post-surgery recovery support</li><li style="padding:var(--space-xs) 0;">✦ Detoxification & cleansing</li><li style="padding:var(--space-xs) 0;">✦ Gentle & non-invasive</li></ul>' },
];

services.forEach(s => {
    const dir = `services/${s.slug}`;
    mkdirSync(dir, { recursive: true });
    writeFileSync(`${dir}/index.html`, servicePage(s));
    console.log(`✓ ${s.name}`);
});

// ============ BOOKING PAGE ============
// Booking form: when submitted, creates a mailto link with pre-filled details
writeFileSync('book/index.html', pg(
    'Book Mobile Massage London | Same-Day Available',
    `Book mobile massage London same-day. 9 treatments, 30min to 4 hours. Kensington, Mayfair, Paddington, Chelsea, Canary Wharf. 8am-8pm daily. ${PHONE}`,
    '/booking/', `
  <section class="page-hero"><div class="container"><p class="subtitle">Book Online</p><h1>Book Your Mobile Massage</h1><p>Same-day availability. 8am-8pm, 7 days a week across Central London.</p></div></section>
  ${trustBar}
  <section class="section section--white"><div class="container container--narrow">
    <form id="bookingForm" class="form fade-in">
      <div class="form__group"><label class="form__label" for="name">Full Name *</label><input class="form__input" type="text" id="name" name="name" required placeholder="Your full name"></div>
      <div class="form__group"><label class="form__label" for="email">Email *</label><input class="form__input" type="email" id="email" name="email" required placeholder="your@email.com"></div>
      <div class="form__group"><label class="form__label" for="phone">Phone *</label><input class="form__input" type="tel" id="phone" name="phone" required placeholder="Your phone number"></div>
      <div class="form__group"><label class="form__label" for="treatment">Treatment *</label><select class="form__input" id="treatment" name="treatment" required><option value="">— Choose Treatment —</option><option value="Deep Tissue Massage">Deep Tissue Massage (from £65)</option><option value="Swedish Massage">Swedish Massage (from £55)</option><option value="Hot Stone Massage">Hot Stone Massage (from £70)</option><option value="Aromatherapy Massage">Aromatherapy Massage (from £65)</option><option value="Sensual Massage">Sensual Massage (from £120)</option><option value="Massage with Divine Alignment">Divine Alignment (from £80)</option><option value="Sports Recovery Massage">Sports Massage (from £65)</option><option value="Couples Massage">Couples Massage (from £110)</option><option value="Lymphatic Drainage">Lymphatic Drainage (from £65)</option></select></div>
      <div class="form__group"><label class="form__label" for="duration">Duration *</label><select class="form__input" id="duration" name="duration" required><option value="">— Choose Duration —</option><option value="30 minutes">30 Minutes</option><option value="60 minutes">60 Minutes</option><option value="90 minutes">90 Minutes</option><option value="2 hours">2 Hours</option><option value="3 hours">3 Hours</option><option value="4 hours">4 Hours</option></select></div>
      <div class="form__group"><label class="form__label" for="date">Preferred Date *</label><input class="form__input" type="date" id="date" name="date" required></div>
      <div class="form__group"><label class="form__label" for="time">Preferred Time *</label><select class="form__input" id="time" name="time" required><option value="">— Choose Time —</option><option value="8:00 AM">8:00 AM</option><option value="9:00 AM">9:00 AM</option><option value="10:00 AM">10:00 AM</option><option value="11:00 AM">11:00 AM</option><option value="12:00 PM">12:00 PM</option><option value="1:00 PM">1:00 PM</option><option value="2:00 PM">2:00 PM</option><option value="3:00 PM">3:00 PM</option><option value="4:00 PM">4:00 PM</option><option value="5:00 PM">5:00 PM</option><option value="6:00 PM">6:00 PM</option><option value="7:00 PM">7:00 PM</option><option value="8:00 PM">8:00 PM</option></select></div>
      <div class="form__group"><label class="form__label" for="address">Address (Postcode) *</label><input class="form__input" type="text" id="address" name="address" required placeholder="e.g. W8 5SA"></div>
      <div class="form__group"><label class="form__label" for="notes">Additional Notes</label><textarea class="form__input" id="notes" name="notes" rows="3" placeholder="Any health conditions, allergies, or special requests..."></textarea></div>
      <button type="submit" class="btn btn--primary btn--lg" style="width:100%;">Book Now — Send Request</button>
      <p style="text-align:center;margin-top:var(--space-md);color:var(--color-muted);font-size:var(--fs-small);">Or call directly: <a href="${PHONE_LINK}" style="color:var(--color-gold);">${PHONE}</a></p>
    </form>
  </div></section>
  <script>
  document.getElementById('bookingForm').addEventListener('submit', function(e) {
    e.preventDefault();
    const name = document.getElementById('name').value;
    const email = document.getElementById('email').value;
    const phone = document.getElementById('phone').value;
    const treatment = document.getElementById('treatment').value;
    const duration = document.getElementById('duration').value;
    const date = document.getElementById('date').value;
    const time = document.getElementById('time').value;
    const address = document.getElementById('address').value;
    const notes = document.getElementById('notes').value;
    const subject = encodeURIComponent('Massage Booking Request — ' + treatment);
    const body = encodeURIComponent(
      'BOOKING REQUEST\\n\\n' +
      'Name: ' + name + '\\n' +
      'Email: ' + email + '\\n' +
      'Phone: ' + phone + '\\n' +
      'Treatment: ' + treatment + '\\n' +
      'Duration: ' + duration + '\\n' +
      'Date: ' + date + '\\n' +
      'Time: ' + time + '\\n' +
      'Address/Postcode: ' + address + '\\n' +
      'Notes: ' + (notes || 'None') + '\\n\\n' +
      'Sent from massage-london-bereza.vercel.app booking form'
    );
    window.location.href = 'mailto:${EMAIL}?subject=' + subject + '&body=' + body;
  });
  </script>
  <section class="cta-section"><div class="container"><p class="subtitle">Prefer to Call?</p><h2>Book by Phone</h2><p>Call Iryna directly for same-day bookings.</p><a href="${PHONE_LINK}" class="btn btn--primary btn--lg">${PHONE}</a></div></section>`
));
console.log('✓ Booking');

// ============ PRICING ============
writeFileSync('pricing/index.html', pg(
    'Massage Therapy Prices London | From £55 | No Hidden Fees',
    `Transparent massage pricing London. 30 minutes to 4 hours. 9 specialist treatments. All travel included. No hidden fees. The Bereza Method. Kensington, Mayfair, Paddington.`,
    '/pricing/', `
  <section class="page-hero"><div class="container"><p class="subtitle">Pricing</p><h1>Transparent Pricing — No Hidden Fees</h1><p>All prices include travel within Central London, premium organic oils, and all equipment.</p></div></section>
  ${trustBar}
  <section class="section section--white"><div class="container">
    <div class="section-header fade-in"><p class="subtitle">Our Prices</p><h2>From £55 — Everything Included</h2></div>
    <div style="overflow-x:auto;" class="fade-in">
      <table class="pricing-table" style="width:100%;border-collapse:collapse;text-align:left;">
        <thead><tr style="border-bottom:2px solid var(--color-gold);"><th style="padding:var(--space-md);font-family:var(--ff-heading);">Treatment</th><th style="padding:var(--space-md);">30 min</th><th style="padding:var(--space-md);">60 min</th><th style="padding:var(--space-md);">90 min</th><th style="padding:var(--space-md);">2 hrs</th></tr></thead>
        <tbody>
          <tr style="border-bottom:1px solid var(--color-light-gray);"><td style="padding:var(--space-md);font-weight:600;">Swedish Massage</td><td style="padding:var(--space-md);">£55</td><td style="padding:var(--space-md);">£85</td><td style="padding:var(--space-md);">£115</td><td style="padding:var(--space-md);">£150</td></tr>
          <tr style="border-bottom:1px solid var(--color-light-gray);"><td style="padding:var(--space-md);font-weight:600;">Deep Tissue Massage</td><td style="padding:var(--space-md);">£65</td><td style="padding:var(--space-md);">£95</td><td style="padding:var(--space-md);">£130</td><td style="padding:var(--space-md);">£170</td></tr>
          <tr style="border-bottom:1px solid var(--color-light-gray);"><td style="padding:var(--space-md);font-weight:600;">Hot Stone Massage</td><td style="padding:var(--space-md);">£70</td><td style="padding:var(--space-md);">£105</td><td style="padding:var(--space-md);">£140</td><td style="padding:var(--space-md);">£180</td></tr>
          <tr style="border-bottom:1px solid var(--color-light-gray);"><td style="padding:var(--space-md);font-weight:600;">Aromatherapy</td><td style="padding:var(--space-md);">£65</td><td style="padding:var(--space-md);">£95</td><td style="padding:var(--space-md);">£130</td><td style="padding:var(--space-md);">£170</td></tr>
          <tr style="border-bottom:1px solid var(--color-light-gray);"><td style="padding:var(--space-md);font-weight:600;">Sports Massage</td><td style="padding:var(--space-md);">£65</td><td style="padding:var(--space-md);">£95</td><td style="padding:var(--space-md);">£130</td><td style="padding:var(--space-md);">£170</td></tr>
          <tr style="border-bottom:1px solid var(--color-light-gray);"><td style="padding:var(--space-md);font-weight:600;">Lymphatic Drainage</td><td style="padding:var(--space-md);">£65</td><td style="padding:var(--space-md);">£95</td><td style="padding:var(--space-md);">£130</td><td style="padding:var(--space-md);">£170</td></tr>
          <tr style="border-bottom:1px solid var(--color-light-gray);"><td style="padding:var(--space-md);font-weight:600;">Divine Alignment</td><td style="padding:var(--space-md);">£80</td><td style="padding:var(--space-md);">£120</td><td style="padding:var(--space-md);">£160</td><td style="padding:var(--space-md);">£200</td></tr>
          <tr style="border-bottom:1px solid var(--color-light-gray);"><td style="padding:var(--space-md);font-weight:600;">Couples Massage</td><td style="padding:var(--space-md);">£110</td><td style="padding:var(--space-md);">£165</td><td style="padding:var(--space-md);">£220</td><td style="padding:var(--space-md);">£290</td></tr>
          <tr><td style="padding:var(--space-md);font-weight:600;">Sensual Massage</td><td style="padding:var(--space-md);">—</td><td style="padding:var(--space-md);">£120</td><td style="padding:var(--space-md);">£180</td><td style="padding:var(--space-md);">£240</td></tr>
        </tbody>
      </table>
    </div>
    <p style="text-align:center;margin-top:var(--space-xl);color:var(--color-muted);">All prices include travel within Central London, premium organic oils, professional massage table & fresh linens.</p>
  </div></section>
  <section class="cta-section"><div class="container"><p class="subtitle">Ready to Book?</p><h2>Same-Day Availability</h2><p>Book online or call directly. 8am-8pm, 7 days a week.</p><div style="display:flex;gap:var(--space-md);justify-content:center;flex-wrap:wrap;"><a href="/book/" class="btn btn--primary btn--lg">Book Online</a><a href="${PHONE_LINK}" class="btn btn--outline btn--lg" style="border-color:var(--color-cream);color:var(--color-cream);">Call ${PHONE}</a></div></div></section>`
));
console.log('✓ Pricing');

console.log('Part 2 complete');
